# -*- coding: utf-8 -*-
"""
Created on Fri Jul  4 22:36:49 2025

@author: Bri
"""

class DefaultConcepts:
    defaultConceptualLinks = [
            ["forest","tropical forest",0.3],
            ["forest","boreal forest",0.3],
            ["elevation","hills",0.3],
            ["temperature","desert",0.2],
            ["rainfall","tropical forest",0.4],
            ["vegetation","forest",0.4],
            ["fertility","food",0.2],
            ["metallicity","metallurgy",0.2],
            ["herbivores","food",0.4],
            ["carnivores","fear",0.6],
            ["fear","death",0.4],
            ["rivers","swimming",0.4],
            ["swimming","water",0.4],
            ["shrubland","savanna",0.4],
            ["frost","tundra",0.3],
            ["frost","boreal forest",0.4],
            ["fear","darkness",0.5],
            ["frost","ice",0.3],
            ["fields","savanna",0.5],
            ["fertility","fields",0.4],
            ["nature","vegetation",0.2],
            ["growth","vegetation",0.2],
            ["vegetation","plantlife",0.2],
            ["darkness","fear",0.4],
            ["sky","sunlight",0.3],
            ["ice","latitude",0.5],
            ["travelers","movement",0.3],
            ["sky","constellations",0.4],
            ["metallicity","earth",0.3],
            ["craftsmen","metallurgy",0.4],
            ["superstition","worship",0.4],
            ["builders","defense",0.5],
            ["warriors","weaponry",0.3],
            ["metallurgy","metallurgists",0.1],
            ["traders","transportation",0.9],
            ["sailors","transporation",0.4],
            ["travelers","transportation",0.2],
            ["astrology","constellations",0.2],
            ["research","philosophy",0.5],
            ["shamans","superstition",0.3],
            ["simplicity","nature",0.4],
            ["individualism","traders",0.5],
            ["traders","sailors",0.5],
            ["materialism","research",0.9],
            ["agriculture","fertility",0.5],
            ["naturalism","nature",0.2],
            ["traders","greed",0.5],
            ["magic","philosophy",1],
            ["magic","worship",0.8],
            ["art","philosophy",0.8],
            ["philosophy","government",0.6],
            ["food","agriculture",0.4],
            ["collectivism","government",0.5],
            ["builders","metallurgy",0.4],
            ["sailors","rivers",0.2],
            ["sailors","water",0.2],
            ["water","rivers",0.2],
            ["growth","fertility",0.3],
            ["movement","transportation",0.2],
            ["latitude","darkness",0.5],
            ["production","builders",0.3],
            ["medicine","research",0.5],
            ["production","metallurgy",0.5],
            ["ruins","death",0.5],
            ["weaponry","metallurgy",0.5],
            ["warriors","fear",0.8],
            ["warriors","death",0.9],
            ["astrology","philosophy",0.8],
            ["sunlight","worship",0.8],
            ["sunlight","growth",0.6],
            ["sunlight","temperature",0.3],
            ["hills","mountains",0.2],
            ["mountains","frost",0.5],
            ["elevation","sky",0.5],
            ["warriors","carnivores",0.7],
            ["materialism","production",0.6],
            ["craftsmen","builders",0.4],
            ["shamans","astrology",0.8],
            ["greed","fear",1],
            ["individualism","philosophy",1],
            ["collectivism","philosophy",1],
            ["craftsmen","production",0.4],
            ["vegetation","shrublands",0.6],
            ["vegetation","savanna",0.7],
            ["vegetation","boreal forest",0.5],
            ["vegetation","tropical forest",0.4],
            ["rainfall","water",0.3],
            ["fertility","rainfall",0.5],
            ["water","growth",0.7],
            ["rainfall","sky",0.5],
            ["worship","fear",0.9],
            ["medicine","growth",0.9],
            ["simplicity","philosophy",0.7],
            ["earth","nature",0.7],
            ["art","nature",0.8],
            ["art","research",0.9],
            ["art","magic",0.9],
            ["craftsmen","art",0.8],
            ["tundra","ice",0.3],
            ["art","constellations",0.8],
            ["art","sky",0.9],
            ["art","worship",0.9],
            ["art","fear",0.9],
            ["magic","shamans",0.4],
            ["magic","astrology",0.7],
            ["magic","superstition",0.5],
            ["elevation","mountains",0.2],
            ["rivers","fertility",0.6],
            ["superstition","art",0.8],
            ["defense","weaponry",0.4],
            ["defense","fear",0.8],
            ["defense","warriors",0.6],
            ["temperature","tropical forest",0.6],
            ["desert","savanna",0.6],
            ["desert","shrublands",0.8],
            ["desert","fear",0.8],
            ["desert","sunlight",0.7]
    ]